### ISSUE TITLE
Not working as of now.

### ISSUE THREAD

**Issue by mendelsphotography** [dickermoshe/OpenChaver#3]
If you download the latest version, it does not work.
Needs fixing.

**Comment by dickermoshe** [comment]
I will do dev work on the dev branch. 
Master branch will always be in a working state from now...

**Comment by mendelsphotography** [comment]
Getting this error when runing the to install requirments.txt

ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.13.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime==1.13.1

**Comment by mendelsphotography** [comment]
also 
Traceback (most recent call last):
  File "manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File OpenChaver-master\manage.py", line 22, in <module>
    main()
  File "OpenChaver-master\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by dickermoshe** [comment]
You need Python >=3.10
You got the django error due to the pip command failing.

**Comment by mendelsphotography** [comment]
fixed.
How do I kill it?

**Comment by dickermoshe** [comment]
Disable the services and restart the computer.
Sadly killing is authenticated action that has not been implemented yet.
